name: Format and Lint

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Install Clang Format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Verify Formatting Style
        run: make check-format

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang Tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Run Clang Tidy Linter
        run: make lint
