name: Code Formatting Check

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Run clang-format on all C files
        uses: jidicula/clang-format-action@v4.11.0
        with:
          exclude-regex: 'external'
          include-regex: '.*\.(c|h)$' 
